version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: sharap-mysql
    ports:
      - "3100:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sharapwp
      MYSQL_USER: root
      MYSQL_PASSWORD: wordpress
    volumes:
      - ~/data/sharap:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: sharap-webserver
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: sharapwp
    volumes:
      - ./:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sharap-phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - "2045:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 3000000000
    volumes:
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini
  